.catalog:
  name: "Drupal"
  version: "0.1.1"
  description: "Blog tool, publishing platform and CMS"
  uuid: Drupal-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access the drupal site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: "DB_PASS"
      description: "Database Password to use for the server"
      label: "DB Password"
      required: true
      default: ""
      type: "password"


drupal:
