version: '2'
catalog:
  name: "Rabbit MQ persistent"
  version: "0.3.0"
  decription: A reliable, distributed messaging broker with persistent storage
  questions:
    - variable: "erlang_cookie"
      description: "Erlang cookie required for auth"
      label: "Erlang cookie:"
      required: true
      default: defaultcookiepleasechange
      type: "string"
    - variable: "cluster_partition_handling"
      label: "Partition Handling:"
      description: "Cluster partition handling mode"
      required: true
      type: "enum"
      default: autoheal
      options:
        - autoheal
        - ignore
        - pause_minority
    - variable: "net_ticktime"
      description: "Rabbitmq net ticktime setting"
      label: "Net ticktime:"
      required: false
      type: "int"
      default: 60
    - variable: "confd_args"
      description: "Confd additional args"
      label: "Confd args"
      required: false
      type: "string"
      default: --interval 5
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server"
      label: "VOLUME Driver"
      required: true
      default: "rancher-nfs"
      type: enum
      options: # List of options if using type of `enum`
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: "CONFIG_VOLUME_NAME"
      description: "The CONFIG VOLUME name to associate with this server"
      label: "CONFIG VOLUME Name"
      required: true
      default: ""
      type: "string"

services:
  rabbitmq:
    metadata:
      rabbitmq:
        config:
         node.name: "$${HOSTNAME}"
