version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
services:
  app:
    image: piwik:fpm
    volume_driver: ${VOLUME_DRIVER}
    volumes:
      - ${VOLUME_NAME}:/var/www/html/config
    networks:
    - back
  web:
    image: WebHostingCoopTeam/nginx-tiny-proxy:latest
    links:
      - app
    volumes_from:
      - app
    environment:
      - NGINX_TEMPLATE=piwik
      - NGINX_SRC_HOST=app
      - NGINX_SRC_PORT=9000
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.alias: ${VIRTUAL_HOST}
      traefik.domain: ${VIRTUAL_DOMAIN}
      traefik.acme: true
      traefik.port: 80
    networks:
    - back
    - lb_web
  cron:
    image: piwik:fpm
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    networks:
    - back
