apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  labels:
    name: ${SERVICE_NAME}
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: ${SERVICE_PORT}
  selector:
    name: ${FRONTEND_NAME}
