.catalog:
  name: "K8s Guestbook"
  version: "1.0.0"
  description: "It's a guestbook, I guess"
  maximum_rancher_version: v1.3.99
  questions:
    - variable: "SERVICE_NAME"
      label: "Service Name"
      required: true
      default: "frontend"
      type: "string"
    - variable: "SERVICE_PORT"
      label: "What port to listen on"
      required: true
      type: "int"
      default: 80
    - variable: "FRONTEND_NAME"
      label: "Frontend Name"
      required: true
      default: "frontend"
      type: "string"
    - variable: "FRONTEND_REPLICAS"
      label: "Replicas for the frontend RC"
      required: true
      type: "int"
      default: 3
    - variable: "REDIS_MASTER_NAME"
      label: "Redis Master Name"
      required: true
      default: "redis-master"
      type: "string"
    - variable: "REDIS_SLAVE_NAME"
      label: "Redis Slave Name"
      required: true
      default: "redis-slave"
      type: "string"
