apiVersion: v1
kind: Service
metadata:
  name: ${REDIS_SLAVE_NAME}
  labels:
    name: ${REDIS_SLAVE_NAME}
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
  selector:
    name: ${REDIS_SLAVE_NAME}
