.catalog:
  name: Gitlab WHC
  version: latest
  description: |
    Gitlab CE is a free GitHub alternative with additions by the Webhosting.coop Team
  minimum_rancher_version: v0.56.0-whc
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: gitlab-whc-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: "gitlab_omnipus_prefix"
      label: "Gitlab external_url prefix:"
      description: |
        This is needed for the docker-compose file to set the correct external_url
      default: 'https://'
      required: true
      type: "string"
      options:
        - 'https://'
        - 'http://'
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 80
      type: "string"
    - variable: "https_port"
      description: "HTTPS port to expose on host. Will be used to bind TCP"
      label: "HTTPS port:"
      required: true
      default: 443
      type: "string"
    - variable: "ssh_port"
      description: "SSH port to expose on host. Will be used to bind TCP"
      label: "SSH port:"
      required: true
      default: 22
      type: "string"
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
      label: "VOLUME Driver"
      required: true
      default: "convoy-nfs"
      type: "string"
    - variable: "VOLUME_NAME"
      description: "The VOLUME name to associate with this server"
      label: "VOLUME Name"
      required: true
      default: "ARMA3"
      type: "string"

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true

