mattermost:
  image: joshuacox/mattermost
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: mattermost-datavolume
    io.rancher.container.pull_image: always
    traefik.enable: true
    traefik.alias: ${MATTERMOST_HOST}
    traefik.domain: ${MATTERMOST_DOMAIN}
    traefik.enable: true
    traefik.acme: true
    traefik.port: 80
  environment:
    - MATTERMOST_SECRET_KEY=${MATTERMOST_SECRET_KEY}
    - MATTERMOST_LINK_SALT=${MATTERMOST_LINK_SALT}
    - MATTERMOST_RESET_SALT=${MATTERMOST_RESET_SALT}
    - MATTERMOST_INVITE_SALT=${MATTERMOST_INVITE_SALT}
    - MM_USERNAME=${MM_USERNAME}
    - MM_PASSWORD=${MM_PASSWORD}
    - MM_DBNAME=${MM_DBNAME}
    - DB_HOST=${DB_HOST}
    - DB_PORT_5432_TCP_PORT=${DB_PORT_5432_TCP_PORT}
  volumes_from:
    - mattermost-datavolume

mattermost-datavolume:
  labels:
    io.rancher.container.start_once: true
    io.rancher.container.pull_image: always
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${VOLUME_NAME}:/opt/mattermost/data
  image: busybox
  command: /bin/true
