.catalog:
  name: WWIV WHC
  version: 0.0.1
  description: |
    WWIV is an open source BBS that has origins that reach back to 1984
  minimum_rancher_version: v0.56.0
  maintainer: "Josh Cox <josh@webhosting.coop>"
  uuid: wwiv-whc-0
  questions:
    - variable: "wwiv_host"
      description: "WWIV hostname (without uri scheme http:// or https://)"
      label: "hostname:"
      required: true
      default: "wwiv"
      type: "string"
    - variable: "wwiv_domain"
      description: "WWIV domain (without uri scheme http:// or https://)"
      label: "domain:"
      required: true
      default: "example.com"
      type: "string"

wwiv-data:
  scale: 1
  retain_ip: true

wwiv:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 9
    strategy: none
    response_timeout: 9000
    healthy_threshold: 2
