collector:
  tty: true
  image: webhostingcoopteam/snowplow-scala-collector
  environment:
    - KAFKA_SERVICE=${kafka_link}
  external_links:
    - ${kafka_link}:kafka
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
