version: '2'

services:

  wwiv-data:
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: ${wwiv_host_label}
    command: /bin/true
    image: busybox
    volume_driver: ${VOLUME_DRIVER}
    volumes:
    - ${VOLUME_NAME}:/srv/wwiv:Z

  wwiv:
    restart: always
    image: webhostingcoopteam/wwiv
    ports:
    - "${wwiv_port}:23"
    volumes_from:
    - wwiv-data
    labels:
      io.rancher.sidekicks: wwiv-data
      io.rancher.container.pull_image: always
    hostname: ${wwiv_host}.${wwiv_domain}
