.catalog:
  name: WWIV WHC
  version: 0.0.9
  description: |
    WWIV is an open source BBS that has origins that reach back to 1984
  minimum_rancher_version: v0.56.0
  maintainer: "Josh Cox <josh@webhosting.coop>"
  uuid: wwiv-whc-0
  questions:
    - variable: "wwiv_host"
      description: "WWIV hostname (without uri scheme http:// or https://)"
      label: "hostname"
      required: true
      default: "wwiv"
      type: "string"
    - variable: "wwiv_domain"
      description: "WWIV domain (without uri scheme http:// or https://)"
      label: "domain"
      required: true
      default: "example.com"
      type: "string"
    - variable: "wwiv_telnet_port"
      description: "WWIV telnet port"
      label: "telnet port"
      required: true
      default: "2323"
      type: "string"
    - variable: "wwiv_ssh_port"
      description: "WWIV ssh port"
      label: "ssh port"
      required: true
      default: "2322"
      type: "string"
    - variable: "wwiv_http_port"
      description: "WWIV http port"
      label: "http port"
      required: true
      default: "2380"
      type: "string"
    - variable: "wwiv_bipd_port"
      description: "WWIV bipd port"
      label: "bipd port"
      required: true
      default: "2324"
      type: "string"
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
      label: "VOLUME Driver"
      required: true
      default: "convoy-nfs"
      type: "enum"
      options: # List of options if using type of `enum`
        - convoy-nfs
        - convoy-efs
        - convoy-ebs
    - variable: "VOLUME_NAME"
      description: "The VOLUME name to associate with this server"
      label: "VOLUME Name"
      required: true
      default: "WWIV"
      type: "string"
    - variable: "wwiv_host_label"
      description: "Host label where to run WWIV service."
      label: "WWIV Host label:"
      required: true
      default: "WWIV=true"
      type: "string"

wwiv-data:
  scale: 1
  retain_ip: true

wwiv:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 9
    strategy: none
    response_timeout: 9000
    healthy_threshold: 2
