apiVersion: v1
kind: ReplicationController
metadata:
  namespace: ${NAMESPACE}
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress
spec:
  replicas: ${REPLICAS}
  selector:
    k8s-app: traefik-ingress
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
        name: traefik-ingress
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.0.2
        name: traefik-ingress
        ports:
        - containerPort: 80
          hostPort: ${http_port}
        - containerPort: 443
          hostPort: ${https_port}
        - containerPort: 8080
          hostPort: ${admin_port}
        args:
        - --web
        - --kubernetes
        #- --logLevel=DEBUG
      nodeSelector:
        traefik_lb: "true"
