apiVersion: v1
kind: Service
metadata:
  name: prom-rancher-exporter
  namespace: "default"
spec:

  ports:
  - name: prometheus-rancher-exporter
    port: 9010
    protocol: TCP
  selector:
    name: prometheus-rancher-exporter