apiVersion: v1
kind: Service
metadata:
  name: ranch-eye
  labels:
    io.rancher.scheduler.global: "true"
    io.rancher.container.dns: "true"
spec:
  ports:
  - port: 9104
    protocol: TCP
    targetPort: 9104
  selector:
    name: ranch-eye
