.catalog:
  name: Redis
  version: 2.8.23-rancher1
  description: A highly-available in-memory data structure store
  maximum_rancher_version: v1.3.99
  questions:
    - variable: "REDIS_REPLICAS"
      label: "Initial number of Redis nodes"
      required: true
      type: "int"
      default: 3
    - variable: "SENTINEL_REPLICAS"
      label: "Initial number of Redis Sentinel nodes"
      required: true
      type: "int"
      default: 3
