version: '2'
services:
  oauth-proxy:
    image: ${OAUTH_TAG}
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.alias: ${PROXIED_HOST}
      traefik.domain: ${PROXIED_DOMAIN}
      traefik.acme: true
      traefik.port: 4180
    environment:
      UPSTREAM: http://${PROXIED_SRC_HOST}:${PROXIED_SRC_PORT}
      PROVIDER:  ${OAUTH2_PROVIDER}
      EMAIL_DOMAIN:  ${OAUTH2_EMAIL_DOMAIN}
      OAUTH2_PROXY_ARGS: ${OAUTH2_PROXY_ARGS}
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_COOKIE_NAME: ${OAUTH2_PROXY_COOKIE_NAME}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_SIGNATURE_KEY: ${OAUTH2_PROXY_SIGNATURE_KEY}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_COOKIE_DOMAIN: ${OAUTH2_PROXY_COOKIE_DOMAIN}
      OAUTH2_PROXY_COOKIE_EXPIRE: ${OAUTH2_PROXY_COOKIE_EXPIRE}
      OAUTH2_PROXY_COOKIE_REFRESH: ${OAUTH2_PROXY_COOKIE_REFRESH}
