version: '2'
catalog:
  name: Piwik
  version: 0.0.1
  upgrade_from: 0.0.0
  description: |
    Piwik for analytics
  questions:
  - variable: "VIRTUAL_HOST"
    description: "Hostname to use for the server"
    label: "Piwik Hostname"
    required: true
    default: "piwik"
    type: "string"
  - variable: "VOLUME_NAME"
    description: "The VOLUME name to associate with this server"
    label: "VOLUME Name"
    required: true
    default: "PIWIK"
    type: "string"
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server"
    label: "VOLUME Driver"
    required: true
    default: "rancher-nfs"
    type: enum
    options: # List of options if using type of `enum`
      - rancher-nfs
      - rancher-efs
      - rancher-ebs

services:
  web:
    scale: 1
    retain_ip: true
    health_check:
      port: 80
      interval: 30000
      unhealthy_threshold: 9
      strategy: none
      response_timeout: 9000
      healthy_threshold: 2
