version: '2'
catalog:
  name: Plex
  version: 0.0.1
  upgrade_from: 0.0.0
  description: |
    Plex Media Server
  questions:
  - variable: "TZ"
    description: "Timezone to use for the server"
    label: "Timezone"
    required: true
    default: "America/Chicago"
    type: "string"

  - variable: "PLEX_CLAIM"
    description: "PLEX_CLAIM"
    label: "PLEX_CLAIM"
    required: true
    default: ""
    type: "string"

  - variable: "ADVERTISE_IP"
    description: "ADVERTISE_IP"
    label: "ADVERTISE_IP"
    required: true
    default: ""
    type: "string"

services:
  plex:
    scale: 1
    retain_ip: true
    health_check:
      port: 32400
      interval: 30000
      unhealthy_threshold: 9
      strategy: none
      response_timeout: 9000
      healthy_threshold: 2
