version: '2'

services:

  wwiv-data:
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: ${wwiv_host_label}
      traefik.enable: true
      traefik.alias: ${wwiv_host}
    - variable: "wwiv_host"
      traefik.domain: ${wwiv_domain}
      traefik.acme: true
      traefik.port: 80
    command: /bin/true
    image: busybox
    volume_driver: ${VOLUME_DRIVER}
    volumes:
    - ${VOLUME_NAME}:/srv/wwiv:Z

  wwiv:
    restart: always
    image: webhostingcoopteam/wwiv
    ports:
    - "${wwiv_telnet_port}:23"
    - "${wwiv_ssh_port}:22"
    - "${wwiv_http_port}:80"
    - "${wwiv_bipd_port}:24"
    volumes_from:
    - wwiv-data
    labels:
      io.rancher.sidekicks: wwiv-data
      io.rancher.container.pull_image: always
    hostname: ${wwiv_host}.${wwiv_domain}
