.catalog:
  name: MongoDB
  version: 3.2-rancher1
  description: MongoDB Replica Set
  maximum_rancher_version: v1.3.99
  questions:
    - variable: "sec_no"
      label: "Number of Secondary nodes"
      required: true
      type: int
      default: 2
      description: "should be even number"
    - variable: "mongo_volume"
      label: "hostpath volume for mongodb"
      required: true
      type: string
      default: "/data/db"
