version: '2'
catalog:
  name: OpenEMR WHC
  version: 0.0.9
  description: |
    openemr CE is a free GitHub alternative with additions by the Webhosting.coop Team
  minimum_rancher_version: v0.56.0
  maintainer: "Josh Cox <josh@webhosting.coop>"
  uuid: openemr-whc-0
  questions:
    - variable: "openemr_host"
      description: "openemr hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "openemr"
      type: "string"
    - variable: "openemr_domain"
      description: "openemr hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "example.com"
      type: "string"
    - variable: "TAG"
      description: "TAG"
      label: "TAG"
      required: true
      default: "latest"
      type: "string"
    - variable: "MYSQL_ROOT_PASSWORD"
      description: "MySQL root password"
      label: "MySQLROOTPASS"
      required: true
      default: ""
      type: "password"
    - variable: host_label
      label: "Host Label to run openemr"
      description: |
        Host label to use as openemr 'value' tag.
        Example: 'openemr=true'
      required: false
      default: "private=true"
      type: "string"
    - variable: "OPENEMR_COMMAND"
      description: "Useful for debugging"
      label: "command"
      required: true
      default: "/assets/start"
      type: "string"

services:
  openemr:
    scale: 1
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 360000
      unhealthy_threshold: 9
      strategy: none
      healthy_threshold: 2
      response_timeout: 9000
  db:
    scale: 1
    retain_ip: true
  openemr-data:
    scale: 1
    retain_ip: true
