---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: kube-system
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://Kubernetes.kubernetes:6443?inClusterConfig=true&insecure=true
        - --sink=influxdb:http://monitoring-influxdb:8086
