apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: ghost-lb
  name: ghost-lb
spec: 
  ports:
    - port: 80
      targetPort: 2368
  selector: 
    name: ghost
    app: ghost
  type: LoadBalancer
