name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster
version: 3.4.9-k8s1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk