.catalog:
  name: Redmine
  version: 0.1.3
  description: |
    Redmine for email settings see the docs here http://www.redmine.org/projects/redmine/wiki/EmailConfiguration
  questions:
  - variable: "REDMINE_HOST"
    description: "Hostname to use for the redmine server"
    label: "REDMINE Hostname"
    required: true
    default: ""
    type: "string"
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Redmine listen on?"
    default: 10083
    required: true
  - variable: "VOLUME_NAME"
    description: "Work volume to save redmine data"
    label: "Work volume:"
    required: true
    default: "REDMINE"
    type: "string"
  - variable: "PG_VOLUME_NAME"
    description: "Postgres Work volume to save redmine data"
    label: "Postgres Work volume:"
    required: true
    default: "REDMINE_PG"
    type: "string"
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
    label: "VOLUME Driver"
    required: true
    default: "convoy-nfs"
    type: "string"
  - variable: "DB_PASS"
    description: "Database Password to use for the server"
    label: "DB Password"
    required: true
    default: ""
    type: "password"
  - variable: "SMTP_HOST"
    description: "SMTP Host to use for the server"
    label: "SMTP Host"
    required: true
    default: ""
    type: "string"
  - variable: "SMTP_DOMAIN"
    description: "SMTP DOMAIN to use for the server"
    label: "SMTP DOMAIN"
    required: true
    default: ""
    type: "string"
  - variable: "SMTP_ENABLED"
    description: "SMTP ENABLED"
    label: "SMTP ENABLED"
    required: true
    default: ""
    type: "boolean"
  - variable: "SMTP_USER"
    description: "SMTP User to use for the server"
    label: "SMTP User"
    required: true
    default: ""
    type: "string"
  - variable: "SMTP_AUTHENTICATION"
    description: "SMTP Authentication to use for the server"
    label: "SMTP User"
    required: true
    default: ":login"
    type: "string"
  - variable: "SMTP_PASS"
    description: "SMTP Password to use for the server"
    label: "SMTP Password"
    required: true
    default: ""
    type: "password"
  - variable: "TZ"
    description: "Timezone to use for the server"
    label: "Timezone"
    required: true
    default: "America/Chicago"
    type: "string"
