name: "Weave Cloud Agents"
description: |
    Weave Cloud is a add-on to Kubernetes which provides Continuous Delivery, along with hosted Prometheus Monitoring and a visual dashboard for exploring & debugging microservices
version: "latest"
category: "Continuous Delivery, Monitoring & Debugging"
maintainer: "Ilya Dmitrichenko <ilya@weave.works>"
