version: '2'
services:
  receive:
    command:
      - receive
    external_links:
      - ${rabbitmq_link}:rabbitmq
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
      - AMQ_HOST=rabbit
  send:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
      - AMQ_HOST=rabbit
    command:
      - send
    external_links:
      - ${rabbitmq_link}:rabbitmq

  worker:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
      - AMQ_HOST=rabbit
    command:
      - worker
    external_links:
      - ${rabbitmq_link}:rabbitmq
  newtask:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
      - AMQ_HOST=rabbit
    command:
      - new_task
    external_links:
      - ${rabbitmq_link}:rabbitmq

  rpcserver:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
      - AMQ_HOST=rabbit
    command:
      - rpc_server
    external_links:
      - ${rabbitmq_link}:rabbitmq
  rpcclient:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
      - AMQ_HOST=rabbit
    command:
      - rpc_client
      - '5'
    external_links:
      - ${rabbitmq_link}:rabbitmq

  receivelogs:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
      - AMQ_HOST=rabbit
    command:
      - receive_logs
    external_links:
      - ${rabbitmq_link}:rabbitmq
  emitlog:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
      - AMQ_HOST=rabbit
    command:
      - emit_log
    external_links:
      - ${rabbitmq_link}:rabbitmq

  receivelogsdirect:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
      - AMQ_HOST=rabbit
    command:
      - receive_logs_direct
    external_links:
      - ${rabbitmq_link}:rabbitmq
  emitlogdirect:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
      - AMQ_HOST=rabbit
    command:
      - emit_log_direct
    external_links:
      - ${rabbitmq_link}:rabbitmq

  receivelogstopic:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
      - AMQ_HOST=rabbit
    command:
      - receive_logs_topic
    external_links:
      - ${rabbitmq_link}:rabbitmq
  emitlogtopic:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
      - AMQ_HOST=rabbit
    command:
      - emit_log_topic
    external_links:
      - ${rabbitmq_link}:rabbitmq
