version: '2'

services:
  redmine-datavolume:
    image: "busybox"
    volume_driver: ${VOLUME_DRIVER}
    volumes:
      - ${VOLUME_NAME}:/home/redmine/data
      - ${PG_VOLUME_NAME}:/var/lib/postgresql/data
    labels:
      io.rancher.container.start_once: true
    entrypoint: ["/bin/true"]

  postgresql:
    restart: always
    image: postgres:9.6-alpine
    volumes_from:
    - redmine-datavolume
    labels:
      io.rancher.sidekicks: redmine-datavolume
      io.rancher.container.pull_image: always
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}
    - POSTGRES_DB=${DB_NAME}
    - PGDATA='/var/lib/postgresql/data'

  redmine:
    image: sameersbn/redmine:3.3.2
    labels:
      io.rancher.sidekicks: postgresql,redmine-datavolume
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.alias: ${REDMINE_HOST}
      traefik.domain: ${REDMINE_DOMAIN}
      traefik.acme: true
      traefik.port: 80
    environment:
    - REDMINE_HOST=${REDMINE_HOST}
    - REDMINE_DOMAIN=${REDMINE_DOMAIN}
    - PORT=${PORT}
    - VOLUME_NAME=${VOLUME_NAME}
    - PG_VOLUME_NAME=${PG_VOLUME_NAME}
    - VOLUME_DRIVER=${VOLUME_DRIVER}
    - TZ=${TZ}
    - DB_PASS=${DB_PASS}
    - DB_ADAPTER=${DB_ADAPTER}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    - DB_NAME=${DB_NAME}
    - REDMINE_HTTPS=${REDMINE_HTTPS}
    - REDMINE_RELATIVE_URL_ROOT=${REDMINE_RELATIVE_URL_ROOT}
    - REDMINE_SECRET_TOKEN=${REDMINE_SECRET_TOKEN}
    - REDMINE_SUDO_MODE_ENABLED=${REDMINE_SUDO_MODE_ENABLED}
    - REDMINE_SUDO_MODE_TIMEOUT=${REDMINE_SUDO_MODE_TIMEOUT}
    - REDMINE_CONCURRENT_UPLOADS=${REDMINE_CONCURRENT_UPLOADS}
    - REDMINE_BACKUP_SCHEDULE=${REDMINE_BACKUP_SCHEDULE}
    - REDMINE_BACKUP_EXPIRY=${REDMINE_BACKUP_EXPIRY}
    - REDMINE_BACKUP_TIME=${REDMINE_BACKUP_TIME}
    - SMTP_ENABLED=${SMTP_ENABLED}
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
    - SMTP_METHOD=${SMTP_METHOD}
    - SMTP_DOMAIN=${SMTP_DOMAIN}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASS=${SMTP_PASS}
    - SMTP_STARTTLS=${SMTP_STARTTLS}
    - IMAP_ENABLED=${IMAP_ENABLED}
    - IMAP_HOST=${IMAP_HOST}
    - IMAP_PORT=${IMAP_PORT}
    - IMAP_USER=${IMAP_USER}
    - IMAP_PASS=${IMAP_PASS}
    - IMAP_SSL=${IMAP_SSL}
    - IMAP_INTERVAL=${IMAP_INTERVAL}
    ports:
    - "${PORT}:80"
    volumes_from:
    - redmine-datavolume
