apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: wpfrontend
  name: wpfrontend
spec: 
  ports:
    - port: ${SERVICE_PORT}
  selector: 
    name: wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels: 
    name: wordpress
spec: 
  containers: 
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: ${WP_PASSWORD}
      ports: 
        - containerPort: ${SERVICE_PORT}
          name: wordpress
      volumeMounts:
        - name: wordpress-ephemeral-storage
          mountPath: /var/www/html
  volumes:
    - name: wordpress-ephemeral-storage
      emptyDir: {}
