.catalog:
  name: "Drupal"
  version: "0.1.0"
  description: "Blog tool, publishing platform and CMS"
  uuid: Drupal-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access the drupal site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: "VOLUME_NAME"
      description: "Work volume to save redmine data"
      label: "Work volume:"
      required: true
      default: "DRUPAL"
      type: "string"
    - variable: "DB_VOLUME_NAME"
      description: "DB Work volume to save redmine data"
      label: "DB Work volume:"
      required: true
      default: "DRUPAL_DB"
      type: "string"
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
      label: "VOLUME Driver"
      required: true
      default: "convoy-nfs"
      type: "string"
    - variable: "DB_PASS"
      description: "Database Password to use for the server"
      label: "DB Password"
      required: true
      default: ""
      type: "password"


drupal:
