version: '2'
catalog:
  name: OpenEMR WHC
  version: 0.1.1
  description: |
    openemr CE is a free GitHub alternative with additions by the Webhosting.coop Team
  minimum_rancher_version: v0.56.0
  maintainer: "Josh Cox <josh@webhosting.coop>"
  uuid: openemr-whc-0
  questions:
    - variable: "openemr_host"
      description: "openemr hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "openemr"
      type: "string"
    - variable: "openemr_domain"
      description: "openemr hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "example.com"
      type: "string"
    - variable: "TAG"
      description: "TAG"
      label: "TAG"
      required: true
      default: "webhostingcoopteam/openemr:latest"
      type: "string"
    - variable: "DB_USER"
      description: "MySQL database user"
      label: "MySQLUSER"
      required: true
      default: "openemr"
      type: "string"
    - variable: "DB_NAME"
      description: "MySQL database name"
      label: "MySQLUSER"
      required: true
      default: "openemr"
      type: "string"
    - variable: "DB_PASS"
      description: "MySQL database password"
      label: "MySQLPASS"
      required: true
      default: ""
      type: "password"
    - variable: "DB_ROOT_PASS"
      description: "MySQL root password"
      label: "MySQLROOTPASS"
      required: true
      default: ""
      type: "password"

services:
  openemr:
    scale: 1
    retain_ip: true
    health_check:
      port: 80
      interval: 30000
      unhealthy_threshold: 9
      strategy: none
      response_timeout: 9000
      healthy_threshold: 2
  db:
    scale: 1
    retain_ip: true
  openemr-data:
    scale: 1
    retain_ip: true
