apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    provider: rabbitmq
    heritage: helm
spec:
  ports:
  - port: ${SERVICE_PORT}
    targetPort: 5672
  selector:
    provider: rabbitmq
