.catalog:
  name: RabbitMQ
  version: 3.6.0-rancher1
  description: A reliable, distributed messaging broker
  maximum_rancher_version: v1.3.99
  questions:
    - variable: REPLICAS
      default: 1
      min: 1
      max: 1
      label: Server Replicas
      description: Initial number of server replicas
      required: true
      type: int
    - variable: SERVICE_PORT
      default: 5672
      label: Service port
      description: Port to expose the service on
      required: true
      type: int
