version: '2'
services:
  receive:
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - receive
    external_links:
      - ${rabbitmq_link}:rabbitmq
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
  send:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - send
    external_links:
      - ${rabbitmq_link}:rabbitmq

  worker:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - worker
    external_links:
      - ${rabbitmq_link}:rabbitmq
  new_task:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - new_task
    external_links:
      - ${rabbitmq_link}:rabbitmq

  rpc_server:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - rpc_server
    external_links:
      - ${rabbitmq_link}:rabbitmq
  rpc_client:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - rpc_client
      - 5
    external_links:
      - ${rabbitmq_link}:rabbitmq

  receive_logs:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - receive_logs
    external_links:
      - ${rabbitmq_link}:rabbitmq
  emit_log:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - emit_log
    external_links:
      - ${rabbitmq_link}:rabbitmq

  receive_logs_direct:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - receive_logs_direct
    external_links:
      - ${rabbitmq_link}:rabbitmq
  emit_log_direct:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - emit_log_direct
    external_links:
      - ${rabbitmq_link}:rabbitmq

  receive_logs_topic:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - receive_logs_topic
    external_links:
      - ${rabbitmq_link}:rabbitmq
  emit_log_topic:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - emit_log_topic
    external_links:
      - ${rabbitmq_link}:rabbitmq
