version: '2'
services:
  receive:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - receive
    external_links:
      - ${rabbitmq_link}:rabbitmq
  send:
    image: joshuacox/rabbitmq-tutorials
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.start_once: true
    environment:
		  AMQ_HOST: rabbitmq
    command:
      - send
    external_links:
      - ${rabbitmq_link}:rabbitmq
